CREATE TABLE IF NOT EXISTS items(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    img VARCHAR(256) NOT NULL,
    title VARCHAR(32) DEFAULT NULL,
    price VARCHAR(32) NOT NULL,
    quantity INT NOT NULL DEFAULT 0
);